services:
  backend:
    build: .
    ports:
      - "3000:3000"
    restart: "always"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: 'numlock11'
      DB_NAME: 'elvturc_db'
      DB_PORT: 3306    
    volumes:
      # - .:/app
      - /app/node_modules
    command: npm run start
  
  frontend:
    build: ./ui
    restart: "always"
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: mysql:latest
    restart: "always"
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "numlock11"
      MYSQL_DATABASE: "elvturc_db"
    volumes:
      - ./dbSource:/var/lib/mysql    # Bind Mount (Uncomment to use)
  
  db-backup:
    image: alpine
    volumes:
      - ./backup.sh:/backup.sh
      - ./dbBackups:/backup
    depends_on:
      - db
    entrypoint: >
      /bin/sh -c "
        apk add --no-cache mysql-client && 
        crontab -l | { cat; echo '0 * * * * /backup.sh'; } | crontab - && 
        crond -f -L /dev/stdout"

