version: '3.8'

services:
  backend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: elvturc_db
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
  
  frontend:
    build: ./ui
    ports:
      - "80:80"
    depends_on:
      - backend

  mysql:
    image: mysql:8
    container_name: elvturc_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: elvturc_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
