# Use Node.js official image
FROM node:18 as build

# Set working directory inside the container
WORKDIR /app

# Copy package.json and install dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy all Angular files and build
COPY . .
RUN npm run build --configuration=production

# Use Nginx to serve the Angular app
FROM nginx:alpine
COPY --from=build /app/dist/ui/browser /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
